#!/bin/bash

source ~/ttsetup/venv/bin/activate

export PDK_ROOT=~/IHP-Open-PDK
export PDK=ihp-sg13g2
export LIBRELANE_TAG=3.0.0rc1

time (\
    ./tt/tt_tool.py --harden --ihp &&\
    ./tt/tt_tool.py --create-png --ihp &&\
    (cd test/ && make -B)\
)

cat runs/wokwi/01-verilator-lint/verilator-lint.log
